AllCops:
  Exclude:
    - 'db/schema.rb' 
    - 'db/migrate/*'
    - 'config/**/*'
    - 'bin/*'
    - 'test/test_helper.rb'
    - 'Guardfile'

Rails:
  Enabled: true

Documentation:
  Enabled: false

MethodLength:
  Max: 15

AbcSize:
  Max: 20

LineLength:
  Max: 100
